In [1]:
import tensorflow as tf

In [7]:
dataset = tf.data.Dataset.from_tensor_slices([1, 2,-1, 3])
for element in dataset:
  print(element)

tf.Tensor(1, shape=(), dtype=int32)
tf.Tensor(2, shape=(), dtype=int32)
tf.Tensor(-1, shape=(), dtype=int32)
tf.Tensor(3, shape=(), dtype=int32)


In [6]:
#what if i want to print only first no   
for element in dataset.take(1):
  print(element)

tf.Tensor(1, shape=(), dtype=int32)


In [8]:
#what if i want to filter based on some condtions
dataset=dataset.filter(lambda x: x > 0)
for element in dataset:
  print(element)

tf.Tensor(1, shape=(), dtype=int32)
tf.Tensor(2, shape=(), dtype=int32)
tf.Tensor(3, shape=(), dtype=int32)


In [9]:
#what if i want to apply some common parameter to all valuse    i can use map()
dataset=dataset.map(lambda x: x*5)
for element in dataset:
  print(element)

tf.Tensor(5, shape=(), dtype=int32)
tf.Tensor(10, shape=(), dtype=int32)
tf.Tensor(15, shape=(), dtype=int32)


In [10]:
# what abount shuffling
dataset=dataset.shuffle(3)
for element in dataset:
  print(element)

tf.Tensor(15, shape=(), dtype=int32)
tf.Tensor(5, shape=(), dtype=int32)
tf.Tensor(10, shape=(), dtype=int32)


In [11]:
#what about batching
dataset=dataset.batch(2)
for element in dataset:
  print(element)

tf.Tensor([ 5 15], shape=(2,), dtype=int32)
tf.Tensor([10], shape=(1,), dtype=int32)


In [12]:
#chaining all the above methods
data=tf.data.Dataset.from_tensor_slices([1, 2,-1, 3])

In [13]:
data.filter(lambda x:x >0).map(lambda y:y*10).shuffle(3).batch(2)
for element in dataset:
  print(element)

tf.Tensor([ 5 10], shape=(2,), dtype=int32)
tf.Tensor([15], shape=(1,), dtype=int32)


#lets work with image data

In [18]:
im_data=tf.data.Dataset.list_files('/content/drive/MyDrive/tensorflow_plural/img*/*/*',shuffle='False')
for file in im_data.take(3):
  print(file)

tf.Tensor(b'/content/drive/MyDrive/tensorflow_plural/img/cat/1633802661589_Labrador Retriever Female Puppy for sale.jpg', shape=(), dtype=string)
tf.Tensor(b'/content/drive/MyDrive/tensorflow_plural/img/dog/1633802908945_Fantail Pigeons for sale.jpg', shape=(), dtype=string)
tf.Tensor(b'/content/drive/MyDrive/tensorflow_plural/img/dog/1633802883923_King Pigeon for sale.jpg', shape=(), dtype=string)


In [19]:
class_name=['cat','dog']
img_count= len(im_data)
img_count

308

# split

In [21]:
train_siz = int(img_count*0.8)
train_ds= im_data.take(train_siz)
test_ds= im_data.skip(train_siz)

In [28]:
s='/content/drive/MyDrive/tensorflow_plural/img/cat/1633802661589_Labrador Retriever Female Puppy for sale.jpg'
s.split('/')[6]

'cat'

In [41]:
def get_label(file_path):

  import os
  return tf.strings.split(file_path,os.path.sep)[6]

In [42]:
def preprocess_img(file_path):
  label= get_label(file_path)
  img= tf.io.read_file(file_path)
  img= tf.image.decode_jpeg(img)
  img= tf.image.resize(img,[128,128])

  return label,img

In [43]:
train_ds.map(get_label)

<MapDataset element_spec=TensorSpec(shape=(), dtype=tf.string, name=None)>

In [46]:
for img,label in train_ds.map(preprocess_img).take(3):
  print('label',label)
  print('img',img)

label tf.Tensor(
[[[181.5625   179.5625   180.5625  ]
  [179.74219  178.07031  178.90625 ]
  [219.39062  219.39062  219.39062 ]
  ...
  [182.98438  189.71094  149.89844 ]
  [138.00781  145.00781   95.484375]
  [116.65625  123.65625   69.82031 ]]

 [[201.20529  199.20529  200.20529 ]
  [198.36603  196.69415  197.53009 ]
  [226.71765  226.71765  226.71765 ]
  ...
  [159.74875  166.68146  126.86896 ]
  [135.55762  143.18784   94.924835]
  [117.451385 125.91797   71.45181 ]]

 [[228.35849  227.53818  227.94833 ]
  [225.02072  224.33499  224.67786 ]
  [237.73584  237.73584  237.73584 ]
  ...
  [153.25159  161.164    121.78006 ]
  [130.53214  138.95792   92.18927 ]
  [107.44858  116.983734  63.491547]]

 ...

 [[ 80.67969   77.67969   72.67969 ]
  [ 84.78906   81.78906   76.78906 ]
  [ 86.46094   83.46094   78.46094 ]
  ...
  [ 46.363983  42.77414   29.54367 ]
  [ 47.38922   43.456512  31.254639]
  [ 56.983368  54.486267  40.765503]]

 [[ 85.44922   82.44922   76.95703 ]
  [ 89.55859   86.55